### ISSUE TITLE
Refactoring wrt coco_

### ISSUE THREAD

**Issue by brockho** [numbbo/numbbo#129]
Shall the prefix "coco_" indicate that it is exposed to the normal user (and it thus should be in coco.h)? In this case, we should move quite some parts of coco.h somewhere else (e.g. coco_allocate_memory, coco_allocate_vector(...), coco_free_memory(...), coco_strdup(...), ...).

**Comment by nikohansen** [comment]
My current thinking would be that `coco_` should be used for global, i.e. non-static (and therefore file-local), identifiers, and for these only. Whether and why `strdup` or `allocate` should/need to be global is to be debated.

**Comment by ttusar** [comment]
At the last meeting we agreed that the prefix `coco_` will be used for all global functions, but also some local ones (such as `coco_strdup()` to separate them from standard library functions). We also said there is no need for the `private_` prefix that was used by some of the "private" methods. 

I have recently removed this prefix and since there is nothing to do w.r.t. `coco_`, I guess we can close this issue.
